export const popular_on_iqiyi = [
  {
    id: 1,
    src: "https://www.themoviedb.org/t/p/original/9iigsYwHsBlU1As6ChDHHTJmVKd.jpg",
    title: "Love Between Fairy and Devil",
    des: "When a low-ranked fairy accidentally resurrects a powerful demon, their fates become cosmically entangled as the world is thrown into turmoil.",
    video_src: "https://www.themoviedb.org/video/play?key=61pxwxsLT6s",
    eps: 36,
  },
  {
    id: 2,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ec8UvuGHlXS87rAyIAmCihcJncw.jpg",
    title: "Wrong Carrage Right Groom",
    des: "During the Tang Dynasty in Yangzhou, two beautiful ladies are due to marry on the same day. Du Bing Yan will wed the seriously ill Qi Tian Lei, the third and prodigal son of the Qi Mansion, while Li Yu Hu must marry the bandit Yuan Bu Qu, who recently kidnapped her martial artist father. En route to their respective grooms' homes, both brides visit the Temple of the Mountain God, which suddenly erupts into flames. In the ensuing chaos, each boards the other's marriage sedan! How will they deal with the consequences of this mistake?",
    video_src: "",
    eps: 24,
  },
  {
    id: 3,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tKU34QiJUfVipcuhAs5S3TdCpAF.jpg",
    title: "Uncanny Counter Season one",
    des: "",
    video_src: "",
    eps: 12,
  },
  {
    id: 4,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/s1zXuYyMMrgpet6BBrMqGlHnvc8.jpg",
    title: "Decendant of the sun",
    des: "",
    video_src: "",
    eps: 8,
  },
  {
    id: 5,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8SXZUWqBS2nPMAzHC3LYVVMaLtd.jpg",
    title: "Laughing Under the Cloud",
    des: "",
    video_src: "",
    eps: 12,
  },
  {
    id: 6,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3gDdorjln7I2JH1vX0o1Uv20jMU.jpg",
    title: "Scrumbag System",
    des: "",
    video_src: "",
    eps: 10,
  },
];

export const top_picks = [
  {
    id: 7,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qKYsrC7dUGBMWLSlHLG8Yy7jmKo.jpg",
    title: "Love is an accident",
    des: "",
    video_src: "",
    eps: 34,
  },
  {
    id: 8,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yrFtRnriHMa4qOkAuXzo7jcXQmp.jpg",
    title: "Love like the Galaxy",
    des: "",
    video_src: "",
    eps: 50,
  },
  {
    id: 9,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uUM4LVlPgIrww07OoEKrGWlS1Ej.jpg",
    title: "The Glry",
    des: "",
    video_src: "",
    eps: 24,
  },
  {
    id: 10,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/oqpzn6xcqqZpk3DB3z3sT6UFkZp.jpg",
    title: "King the land",
    des: "",
    video_src: "",
    eps: 16,
  },
  {
    id: 11,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zVYvodC12ZHGVPHX8LJjZHDERmK.jpg",
    title: "Put your head on my Shoulder",
    des: "",
    video_src: "",
    eps: 24,
  },
  {
    id: 12,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/aZT7iZwR4LE2kk7sXWslgpOP7oT.jpg",
    title: "I am Nobody",
    des: "",
    video_src: "",
    eps: 27,
  },
];

export const c_drama = [
  {
    id: 13,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8TZbpPpLQVS2i7P7yUVhrFlFsmW.jpg",
    title: "The Untamed",
    des: "",
    video_src: "",
    eps: 50,
  },
  {
    id: 14,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/weu4yDKxA26PWgdtzPGIOJ4bJfv.jpg",
    title: "Guardian",
    des: "",
    video_src: "",
    eps: 40,
  },
  {
    id: 15,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mkhWfnBNf6oVEmiLzccZTvafWA6.jpg",
    title: "My Journey to You",
    des: "",
    video_src: "",
    eps: 24,
  },
  {
    id: 16,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5e2owvs9TWVsuIacTFxJGPp6KVW.jpg",
    title: "My Girlfriend is an Alien",
    des: "",
    video_src: "",
    eps: 30,
  },
  {
    id: 17,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sVqP8rGqTrjJtJV9t4UuiPKwLEq.jpg",
    title: "Arsenal Miltary Academy",
    des: "",
    video_src: "",
    eps: 48,
  },
  {
    id: 18,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/op0ZXBZodAc12CVqEN55KxD0FYe.jpg",
    title: "Word of Honor",
    des: "",
    video_src: "",
    eps: 36,
  },
];

export const k_drama = [
  {
    id: 19,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1h4OqxXYRRM2FA3Nu6GBgD3puJj.jpg",
    title: "Sweet Home",
    des: "",
    video_src: "",
    eps: 10,
  },
  {
    id: 20,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bA15g6OLmhQ2HkURRaCztA2jwqI.jpg",
    title: "Our Beloved Summer",
    des: "",
    video_src: "",
    eps: 16,
  },
  {
    id: 21,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/4i2wo2ja5g2PmUxWa1a2eYIboZf.jpg",
    title: "The Witch : Part 1",
    des: "",
    video_src: "",
    eps: 1,
  },
  {
    id: 22,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/icQM4lMTEUVYPrSOV3BH9LZjvmY.jpg",
    title: "The Witch : Part 2",
    des: "",
    video_src: "",
    eps: 1,
  },
  {
    id: 23,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sld43SJArZqlnANJabq8R5wdOZk.jpg",
    title: "True Beauty",
    des: "",
    video_src: "",
    eps: 16,
  },
  {
    id: 24,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vNVFt6dtcqnI7hqa6LFBUibuFiw.jpg",
    title: "Train to Busan",
    des: "",
    video_src: "",
    eps: 1,
  },
];

export const animation = [
  {
    id: 25,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/AnXFYG7y2A65dr5noYvZSdVq8l3.jpg",
    title: "God of Highschool",
    des: "",
    video_src: "",
    eps: 13,
  },
  {
    id: 26,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fcXdJlbSdUEeMSJFsXKsznGwwok.jpg",
    title: "One Piece",
    des: "",
    video_src: "",
    eps: "Update to 1081",
  },
  {
    id: 27,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ecQ84z2sR0XapZu435MnFuEBzD8.jpg",
    title: "Haikyuu",
    des: "",
    video_src: "",
    eps: 25,
  },
  {
    id: 28,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/dACXDyjVUNnUsu1Y7UzdZbRUEvI.jpg",
    title: "Thousand Autumn",
    des: "",
    video_src: "",
    eps: 16,
  },
  {
    id: 29,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg",
    title: "Bleach",
    des: "",
    video_src: "",
    eps: 105,
  },
  {
    id: 30,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5YW0RIlVAhyp3pGtugyNuvk2TWT.jpg",
    title: "Naruto",
    des: "",
    video_src: "",
    eps: 200,
  },
];

export const variety_show = [
  {
    id: 31,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/t5Mco7vVtY2u4gi2YaH6VviVcwH.jpg",
    title: "Youth With You",
    des: "",
    video_src: "",
    eps: 22,
  },
  {
    id: 32,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mHRmru9EIfDYLNprW8Y9JsA3fD1.jpg",
    title: "Girl Planet 999",
    des: "",
    video_src: "",
    eps: 12,
  },
  {
    id: 33,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/epoCnqVnMqohtKnf8QiT1eGaV9A.jpg",
    title: "The Detective's Adventures",
    des: "",
    video_src: "",
    eps: 27,
  },
  {
    id: 34,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/4b6nrG6QYTG3bYyrXpk1wOFoNVy.jpg",
    title: "The Big Band",
    des: "",
    video_src: "",
    eps: 16,
  },
  {
    id: 35,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7MXkkogDg4CLSppNW3sFwD5F36j.jpg",
    title: "Rap for Youth",
    des: "",
    video_src: "",
    eps: 35,
  },
  {
    id: 36,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/r6WaCHNlhkxsp88HciK4IgGOsTF.jpg",
    title: "Fourtry",
    des: "",
    video_src: "",
    eps: 12,
  },
];
