export const popular_on_iqiyi = [
  {
    id: 1,
    src: "https://www.themoviedb.org/t/p/original/9iigsYwHsBlU1As6ChDHHTJmVKd.jpg",
    title: "Love Between Fairy and Devil",
    des: "When a low-ranked fairy accidentally resurrects a powerful demon, their fates become cosmically entangled as the world is thrown into turmoil.",
    video_src: "https://www.youtube.com/embed/HrUeOw7zL40?si=Uw1-4IwmxtTkHXia",
    eps: 36,
  },
  {
    id: 2,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ec8UvuGHlXS87rAyIAmCihcJncw.jpg",
    title: "Wrong Carrage Right Groom",
    des: "During the Tang Dynasty in Yangzhou, two beautiful ladies are due to marry on the same day. Du Bing Yan will wed the seriously ill Qi Tian Lei, the third and prodigal son of the Qi Mansion, while Li Yu Hu must marry the bandit Yuan Bu Qu, who recently kidnapped her martial artist father. En route to their respective grooms' homes, both brides visit the Temple of the Mountain God, which suddenly erupts into flames. In the ensuing chaos, each boards the other's marriage sedan! How will they deal with the consequences of this mistake?",
    video_src: "https://www.youtube.com/embed/4Gyf4sDuQiA?si=nIzpGfuUwUc6a9Jb",
    eps: 24,
  },
  {
    id: 3,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tKU34QiJUfVipcuhAs5S3TdCpAF.jpg",
    title: "Uncanny Counter Season one",
    des: "The story concerns a high school student who is granted incredible powers with which to exorcize evil forces that hold onto souls, preventing them from passing into the afterlife and magnifying their own power. The Uncanny Counter has more classical influences than is typically seen in these kinds of stories today.",
    video_src: "https://www.youtube.com/embed/LOXTIrTcwVk?si=NcRlsENZdhpEQ3Ma",
    eps: 12,
  },
  {
    id: 4,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/s1zXuYyMMrgpet6BBrMqGlHnvc8.jpg",
    title: "Decendant of the sun",
    des: "After a chance meeting in a hospital, an ardent soldier falls for a gifted surgeon. Opposing philosophies tear them apart, but fate has other plans.",
    video_src: "https://www.youtube.com/embed/wkHjOTFv60g?si=wYYqQMkUN26SiJNe",
    eps: 8,
  },
  {
    id: 5,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8SXZUWqBS2nPMAzHC3LYVVMaLtd.jpg",
    title: "Laughing Under the Cloud",
    des: "When swords were outlawed in the eleventh year of the Meiji era, the mighty samurai population began to dwindle. Those who rejected the ban on blades rebelled, causing violent unrest to erupt throughout the countryside. To combat the rise in criminal activity, an",
    video_src: "https://www.youtube.com/embed/LPe2hdEBde0?si=gI9at_D0vvUBL18g",
    eps: 12,
  },
  {
    id: 6,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3gDdorjln7I2JH1vX0o1Uv20jMU.jpg",
    title: "Scrumbag System",
    des: `An ordinary youth--Shen Yuan, after reading the novel "Arrogant Gods and Demons' Journey", triggers the mysterious system so that he crosses into the book world and penetrates into the body of villain--Shen Qingqiu.`,
    video_src: "https://www.youtube.com/embed/WDGV1e469Kc?si=9C8ZRX5za0Kihjqa",
    eps: 10,
  },
];

export const top_picks = [
  {
    id: 7,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qKYsrC7dUGBMWLSlHLG8Yy7jmKo.jpg",
    title: "Love is an accident",
    des: `A girl stumbles upon Jiangjou’s mountaintop pavilion, never imagining she would come to pose as the young master's future wife.`,
    video_src: "https://www.youtube.com/embed/OazlVTc3DYg?si=Qvxj-RvdjlE7jbaT",
    eps: 34,
  },
  {
    id: 8,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yrFtRnriHMa4qOkAuXzo7jcXQmp.jpg",
    title: "Love like the Galaxy",
    des: "A cynical woman who lives alone runs into a powerful general who falls in love with her at first sight. She has trust issues; he has secrets that even he doesn't know about. Together, they start to investigate those secrets.",
    video_src: "https://www.youtube.com/embed/t-78RAN4ibw?si=UNZz4y5gsdnpTOPu",
    eps: 50,
  },
  {
    id: 9,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/uUM4LVlPgIrww07OoEKrGWlS1Ej.jpg",
    title: "The Glory",
    des: "After a childhood marked by pain and violence, a woman puts a carefully planned revenge scheme in motion.",
    video_src: "https://www.youtube.com/embed/tqVVrTvrI8U?si=qLL3oy3XZmVFQjQ3",
    eps: 24,
  },
  {
    id: 10,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/oqpzn6xcqqZpk3DB3z3sT6UFkZp.jpg",
    title: "King the land",
    des: "Amid a tense inheritance fight, a charming heir clashes with his hardworking employee who's known for her irresistible smile — which he cannot stand.",
    video_src: "https://www.youtube.com/embed/AGF16szMOmo?si=M9AVWgc_Fe9XNCOW",
    eps: 16,
  },
  {
    id: 11,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zVYvodC12ZHGVPHX8LJjZHDERmK.jpg",
    title: "Put your head on my Shoulder",
    des: "As Si Tu Mo's graduation is nearing, she is confused about her future plans. Her ordinary days are suddenly shaken up when the genius Physics student Gu Wei Yi appears in her life. The two accidentally end up living together and chaos begins.",
    video_src: "https://www.youtube.com/embed/3ch6s5NJZ34?si=yQnWbHFfCWtdtnV8",
    eps: 24,
  },
  {
    id: 12,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/aZT7iZwR4LE2kk7sXWslgpOP7oT.jpg",
    title: "I am Nobody",
    des: `Zhang Chulan, an ordinary young man, gets entangled in an unprecedented world of "outsiders" when his grandfather's body mysteriously disappears. Facing unexpected pursuit from the Sinister Pleasure, a relentless organization, and the sudden appearance of an enigmatic girl Feng Baobao, Zhang Chulan decides to no longer hide his superpower. As Zhang delves into his grandfather's past, he gradually becomes part of the world of outsiders, where the mysteries of history start to unravel. Behind it all lies a shocking secret, and Feng's mysterious origins seem to hold the key to the truth. The young outsiders fight shoulder to shoulder to overcome the challenges and become friends who have each other's back. On their journey of growth, each one searches for their sense of righteousness, while a battle between good and evil looms on the horizon...`,
    video_src: "https://www.youtube.com/embed/IRkwCNJWCE8?si=h_ijqT7wRgIgHRga",
    eps: 27,
  },
];

export const c_drama = [
  {
    id: 13,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8TZbpPpLQVS2i7P7yUVhrFlFsmW.jpg",
    title: "The Untamed",
    des: "Two talented disciples of respectable magical clans unit during the cultivation training and through many hardships they are together.",
    video_src: "https://www.youtube.com/embed/vRpG1bHIwRU?si=NB-_Xc6coOpAMgqg",
    eps: 50,
  },
  {
    id: 14,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/weu4yDKxA26PWgdtzPGIOJ4bJfv.jpg",
    title: "Guardian",
    des: "Zhao Yunlan, a detective of supernatural phenomena, is tasked to investigate mysterious cases with expert professor, Shen Wei. As they uphold peace between creatures and humans, Yunlan realizes there is more to Shen Wei than meets the eye.",
    video_src: "https://www.youtube.com/embed/8AcNEVUzV4o?si=t8RjvrSQNUzpU321",
    eps: 40,
  },
  {
    id: 15,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mkhWfnBNf6oVEmiLzccZTvafWA6.jpg",
    title: "My Journey to You",
    des: "The series tells the story of Yun Wei Shan, a spy longing for freedom, who infiltrates the palace to complete a mission. Within the eerie and mysterious palace, she encounters love and friendship, embarks on a journey of self-discovery.",
    video_src: "https://www.youtube.com/embed/ZJEYro-6Q44?si=pgztY1L7FZXswrL7",
    eps: 24,
  },
  {
    id: 16,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5e2owvs9TWVsuIacTFxJGPp6KVW.jpg",
    title: "My Girlfriend is an Alien",
    des: "An alien who founds her real love on Earth.",
    video_src: "https://www.youtube.com/embed/m21MWq6wb9Y?si=6mKT-AtU7aGYQc11",
    eps: 30,
  },
  {
    id: 17,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sVqP8rGqTrjJtJV9t4UuiPKwLEq.jpg",
    title: "Arsenal Miltary Academy",
    des: "About a military academy for boys only, but a girl named Xie Xiang joins the academy instead of her brother while pretending to be a boy to make his dream come true. Two men become the object of affection in her life as they engage in many battles to uncover a big conspiracy.",
    video_src: "https://www.youtube.com/embed/L9BlMjnFb5k?si=TxmdRMbVKhlEV33W",
    eps: 48,
  },
  {
    id: 18,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/op0ZXBZodAc12CVqEN55KxD0FYe.jpg",
    title: "Word of Honor",
    des: "Zhou Zi Shu gets embroiled in a conspiracy in the martial arts world. He meets Wen Ke Xing who escapes from the Ghost Valley to avenge his parents' deaths. They become fast friends and embark on an adventure to find a legendary treasure.",
    video_src: "https://www.youtube.com/embed/danLFjQ53aw?si=o39nUWDH8aQSBy7Y",
    eps: 36,
  },
];

export const k_drama = [
  {
    id: 19,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1h4OqxXYRRM2FA3Nu6GBgD3puJj.jpg",
    title: "Sweet Home",
    des: "Hyun, a loner high school student who lost his entire family in a terrible accident, is forced to leave his home and has to face a new reality where monsters are trying to wipe out all of humanity. Now he must fight against all odds to try and race against the clock to save what is left of the human race before it's too late.",
    video_src: "https://www.youtube.com/embed/7rI56NmD33Y?si=9S_WrmSJUdR_JRVY",
    eps: 10,
  },
  {
    id: 20,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/bA15g6OLmhQ2HkURRaCztA2jwqI.jpg",
    title: "Our Beloved Summer",
    des: "A coming of age, romantic comedy revolving around ex-lovers who broke up with a promise never to meet again. But the documentary they filmed ten years ago gets the fame and they are by compulsion facing camera once more.",
    video_src: "https://www.youtube.com/embed/wpW6aVWgvMc?si=lxj3HtjRTE4tlQdc",
    eps: 16,
  },
  {
    id: 21,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/4i2wo2ja5g2PmUxWa1a2eYIboZf.jpg",
    title: "The Witch : Part 1",
    des: "A high school student with amnesia tries to uncover what has happened to her. All leading her into deeper troubles ultimately revealing a darkness she could not have imagined.",
    video_src: "https://www.youtube.com/embed/eYJuGhT5nYs?si=GVGHzZHexbLvYIbC",
    eps: 1,
  },
  {
    id: 22,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/icQM4lMTEUVYPrSOV3BH9LZjvmY.jpg",
    title: "The Witch : Part 2",
    des: "A girl wakes up in a secret laboratory and meets Kyung-hee, who is trying to protect her from a gang. When the gang finally finds the girl, they are overwhelmed by an unexpected power.",
    video_src: "https://www.youtube.com/embed/EgOiCWTR_JU?si=dbspd03xy_esOCf-",
    eps: 1,
  },
  {
    id: 23,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sld43SJArZqlnANJabq8R5wdOZk.jpg",
    title: "True Beauty",
    des: `After being bullied and discriminated because of her ugly looks, a high school girl transforms herself into a gorgeous "goddess" and quickly rises to fame after mastering the art of makeup via online tutorial videos.`,
    video_src: "https://www.youtube.com/embed/Rq3Afp1XGm0?si=5YBJpr6V9Ij1MRDh",
    eps: 16,
  },
  {
    id: 24,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vNVFt6dtcqnI7hqa6LFBUibuFiw.jpg",
    title: "Train to Busan",
    des: "While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan.",
    video_src: "https://www.youtube.com/embed/1ovgxN2VWNc?si=53uYQj0YIL5oIBe0",
    eps: 1,
  },
];

export const animation = [
  {
    id: 25,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/AnXFYG7y2A65dr5noYvZSdVq8l3.jpg",
    title: "God of Highschool",
    des: "A tournament takes place to determine the best fighter among all high school students in Korea.",
    video_src: "https://www.youtube.com/embed/8i3Xvs4R0WY?si=ftmSC1zAyyqlT4Rj",
    eps: 13,
  },
  {
    id: 26,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fcXdJlbSdUEeMSJFsXKsznGwwok.jpg",
    title: "One Piece",
    des: "In a seafaring world, a young pirate captain sets out with his crew to attain the title of Pirate King, and to discover the mythical treasure known as 'One Piece.'",
    video_src: "https://www.youtube.com/embed/fC5MKJDW6sc?si=lXsADOt3x4jd4oQm",
    eps: "Update to 1081",
  },
  {
    id: 27,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ecQ84z2sR0XapZu435MnFuEBzD8.jpg",
    title: "Haikyuu",
    des: `Determined to be like the volleyball championship's star player nicknamed "the small giant", Shoyo joins his school's volleyball club.`,
    video_src: "https://www.youtube.com/embed/gBocyMFO-rU?si=2pk4fMUsW9R-IopP",
    eps: 25,
  },
  {
    id: 28,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/dACXDyjVUNnUsu1Y7UzdZbRUEvI.jpg",
    title: "Thousand Autumn",
    des: "Yan Wushi had walked a path full of blood and corpses. He did not believe in the good nature of humanity. Even more so, he did not believe that there could be someone with great kindness and sense of justice, who would be so considerate of others without asking anything in return. One day, Shen Qiao, who was the sect leader of Mount Xuandu, the number one Daoist sect ...",
    video_src: "https://www.youtube.com/embed/Ciaaqw4ut9w?si=oDlwRVwq3g9u1ywg",
    eps: 16,
  },
  {
    id: 29,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2EewmxXe72ogD0EaWM8gqa0ccIw.jpg",
    title: "Bleach",
    des: "The peace is suddenly broken when warning sirens blare through the Soul Society. Residents are disappearing without a trace and nobody knows who's behind it. Meanwhile, a darkness is approaching Ichigo and his friends in Karakura Town.",
    video_src: "https://www.youtube.com/embed/IUvcnt0yL-c?si=0WIzxTsgFi_tV2xA",
    eps: 105,
  },
  {
    id: 30,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5YW0RIlVAhyp3pGtugyNuvk2TWT.jpg",
    title: "Naruto",
    des: "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja.",
    video_src: "https://www.youtube.com/embed/22R0j8UKRzY?si=-9uzNZKH_l4QFUEZ",
    eps: 200,
  },
];

export const variety_show = [
  {
    id: 31,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/t5Mco7vVtY2u4gi2YaH6VviVcwH.jpg",
    title: "Youth With You",
    des: "Youth with You is a Chinese group survival show that premiered on the iQIYI video platform. Originally titled as Idol Producer 2, it is the second edition of the Chinese group survival show 'Idol Producer'.",
    video_src: "https://www.youtube.com/embed/osu4UrtQ5XY?si=RRIpwI0tKGQYZV1U",
    eps: 22,
  },
  {
    id: 32,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/mHRmru9EIfDYLNprW8Y9JsA3fD1.jpg",
    title: "Girl Planet 999",
    des: "99 contestants participating in the competition. 33 Korean, 33 Japanese, and the last 33 consisted of Chinese, Taiwanese and Hongkongers. They are Competing against each other and people can vote for them base on their performance. The final lineup would be a kpop girl group name KEP1ER consist of 9 members.",
    video_src: "https://www.youtube.com/embed/JHG3NHjiwZ8?si=UmbjvWChODqOYcS8",
    eps: 12,
  },
  {
    id: 33,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/epoCnqVnMqohtKnf8QiT1eGaV9A.jpg",
    title: "The Detective's Adventures",
    des: "The first reality show on detective stories adapted from classic IP. Every episode is based on a classic IP drama. MCs are able to adapt and act out the classic stories in the real scenes. The detective group includes seven MCs, who are encouraged to obtain clues from the unreasonable scripts and amusing games.",
    video_src: "https://www.youtube.com/embed/teqkvGh2Xto?si=Fm7hQafOpwOwepZD",
    eps: 27,
  },
  {
    id: 34,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/4b6nrG6QYTG3bYyrXpk1wOFoNVy.jpg",
    title: "The Big Band",
    des: "We don't have an overview translated in English. Help us expand our database by adding one.",
    video_src: "",
    eps: 16,
  },
  {
    id: 35,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7MXkkogDg4CLSppNW3sFwD5F36j.jpg",
    title: "Rap for Youth",
    des: "We don't have an overview translated in English. Help us expand our database by adding one.",
    video_src: "https://www.youtube.com/embed/6V9MnchVH7w?si=Yv5RJMPGNvnPfsck",
    eps: 35,
  },
  {
    id: 36,
    src: "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/r6WaCHNlhkxsp88HciK4IgGOsTF.jpg",
    title: "Fourtry",
    des: "We don't have an overview translated in English. Help us expand our database by adding one.",
    video_src: "https://www.youtube.com/embed/hPvh5L0p4xA?si=acQIIfI9xmL2MKOX",
    eps: 12,
  },
];
